import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useDispatch } from "react-redux";
import { addToCart } from "@/store/cart/cartSlice";
import ImgCard from "@/components/ImgCard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const dispatch = useDispatch();

  const products = [
    {
      name: "Basmati Rice",
      price: "300",
      description:"Basmati rice is one of the most treasured grains and aging in rice is essential, as it enriches the features of rice by reducing the moisture content",
      image:"rice.webp",
    },
    {
      name: "Desi Moong Dal",
      price: "400",
      description:"A green-skinned dal integral to most Indian kitchens, the moong dal chilka is packed with protein and low on carbs.",
      image:"masoor.webp"
    },
    {
      name: "Sugar",
      price: "100",
      description:"An everyday product used in tea, coffee, milk and other beverages, Nourish Sugar is Sulphur-less sugar",
      image:"sugar.webp"
    },
    {
      name: "Tea",
      price: "500",
      description:"Sip into a nice cuppa tea with Nourish Tea. Handpicked from the best tea estates across Assam and Darjeeling",
      image:"tea.webp"
    },
    {
      name: "Mangodi 200 Gms",
      price: "700",
      description:"Nourish Moong Dal Mangodi is a pakoda or wadi like snack made with a batter of soaked and spiced moong dal.",
      image:"mangodi.webp"
    },
    {
      name: "Multi Grain Atta",
      price: "1000",
      description:"A blend of 6 natural grains – and sourced from fields across the country, our atta is high in fiber which aids in digestion and ensures a healthy gut. ",
      image:"aata.webp"
    },
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="dashboardContainer">
        {/* <h1 onClick={() => dispatch(addToCart(1))}>Add</h1> */}
        <div className="cardContainer flex space-between">
          {products?.map((item,index)=>{
            return(
              <div className="cardItem" key={index}>
                <ImgCard item={item}/>
              </div>
            )
          })}
        </div>
      </div>
    </>
  );
}
